set_unless[:proofgeneral][:dir] = "/opt/"
set_unless[:proofgeneral][:url] = "http://proofgeneral.inf.ed.ac.uk/releases/"
set_unless[:proofgeneral][:package] = "ProofGeneral-4.2.tgz"
set_unless[:proofgeneral][:user] = "dvberkel"
set_unless[:proofgeneral][:group] = "dvberkel"
